# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31d94de939abea808111b1c58e26e2280b1c6ad2b48c6dd978f45cf240bc6fb2756ff1b06ddeff4c07d945384662891daeebd0ed519ab945b42a3dad717dbf1b

test:
  secret_key_base: 5ee968274ebc6bef8448f64c694e7f74d10df375cc77c961909e5b72daf0de2bdf4be7cef78ee16f9f04194e526acdca1f712e2a65a9476331b6621b4a844552

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
